In [1]:
import torch

# Raw Linear Layer
$$ y = x \cdot W+b,$$
$$ where x\in \mathbb R^{n \times M}, y\in \mathbb R^{N\times m}. $$
$$ Thus, W\in \mathbb R^{n\times m} and b\in \mathbb R^m.  $$


In [2]:
# sample data
W = torch.FloatTensor([[1, 2],
                       [3, 4],
                       [5, 6]])
b = torch.FloatTensor([2, 2])

In [3]:
# linear 함수 생성
def linear(x, W, b):
    y = torch.matmul(x, W) + b
    return y

In [4]:
x = torch.FloatTensor([[1, 1, 1],
                       [2, 2, 2],
                       [3, 3, 3],
                       [4, 4, 4]])

In [5]:
y = linear(x, W, b)
print(y)

tensor([[11., 14.],
        [20., 26.],
        [29., 38.],
        [38., 50.]])


## nn.Module
추상화 클래스

두 가지가 중요함.
1. \_\_init__
2. forward

In [6]:
import torch.nn as nn

In [12]:
# 예시
# 여기에는 trainable한 parameters가 없음
class MyLinear(nn.Module):

    def __init__(self, input_dim, output_dim):
        self.input_dim = input_dim
        self.output_dim = output_dim

        super().__init__() # 상위 클래스에서 __init__ 메서드 상속

        self.W = torch.FloatTensor(input_dim, output_dim) # |W| = (input_dim, output_dim)
        self.b = torch.FloatTensor(output_dim)

    # forward 함수를 짜줘야함.
    def forward(self, x):
        # |x| = (batch_size, input_dim)
        y = torch.matmul(x, self.W) + self.b
        # |y| = (batch_size, input_dim) * (input_dim, output_dim)
        #     = (batch_size, output_dim)
        return y

In [10]:
linear = MyLinear(3, 2)
y = linear(x)

In [11]:
y

tensor([[3.7929e-38, 3.9214e-38],
        [6.6582e-38, 6.7592e-38],
        [9.5235e-38, 9.5970e-38],
        [1.2389e-37, 1.2435e-37]])

In [14]:
for p in linear.parameters():
    print(p)

# 아무 것도 나오지 않음

## 제대로 된 방법 

In [13]:
# 예시
# 여기에는 trainable한 parameters가 없음
class MyLinear(nn.Module):

    def __init__(self, input_dim, output_dim):
        self.input_dim = input_dim
        self.output_dim = output_dim

        super().__init__() # 상위 클래스에서 __init__ 메서드 상속

        # nn.Parameter() <- trainable한 파라미터로 사용하겠다는 의미. 이것으로 감싸면 됨.
        self.W = nn.Parameter(torch.FloatTensor(input_dim, output_dim)) # |W| = (input_dim, output_dim)
        self.b = nn.Parameter(torch.FloatTensor(output_dim))

    # forward 함수를 짜줘야함.
    def forward(self, x):
        # |x| = (batch_size, input_dim)
        y = torch.matmul(x, self.W) + self.b
        # |y| = (batch_size, input_dim) * (input_dim, output_dim)
        #     = (batch_size, output_dim)
        return y

In [15]:
linear = MyLinear(3, 2)
y = linear(x) # forward가 매핑되어 있음. 이게 정석적인 방법이다. 

In [16]:
print(y)

tensor([[1.8754e+28, 2.0110e+20],
        [3.7509e+28, 4.0219e+20],
        [5.6263e+28, 6.0329e+20],
        [7.5018e+28, 8.0439e+20]], grad_fn=<AddBackward0>)


In [17]:
for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[0.0000e+00, 3.9214e-38],
        [1.8754e+28, 2.0110e+20],
        [2.1972e-04, 1.0073e-11]], requires_grad=True)
Parameter containing:
tensor([8.9082e-39, 6.9796e-39], requires_grad=True)


## nn.Linear