In [1]:
import torch

## slice

## split
텐서 쪼개기

In [4]:
x = torch.FloatTensor(10, 4)
x

tensor([[ 5.5932e-20,  9.4051e-38,  4.5043e-16,  2.8663e-38],
        [ 5.7800e-39,  7.6442e-38, -4.3872e-22,  7.2063e-15],
        [-7.3890e+14,  2.1184e-22,  3.4971e-21,  2.4430e-38],
        [ 2.2041e-38,  3.6919e-38,  2.2057e-38,  3.6919e-38],
        [ 2.2048e-38,  3.6919e-38,  2.4429e-38,  2.2041e-38],
        [ 3.6919e-38,  9.4051e-38, -7.7998e+29,  2.8866e-14],
        [-2.0798e+29,  5.2846e+05,  1.5555e-39,  7.6442e-38],
        [-4.3872e-22,  7.2063e-15, -7.3890e+14,  2.1184e-22],
        [ 3.4971e-21,  2.6083e-38,  1.5893e-30,  6.5564e-11],
        [ 2.6082e-38, -1.8527e+29,  7.3359e-12,  2.6082e-38]])

In [6]:
splited_tensor = x.split(3)
for tensor in splited_tensor:
    print(tensor.size())

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([1, 4])


In [8]:
splited_tensor = x.split(2, dim=1)
for tensor in splited_tensor:
    print(tensor.size())

torch.Size([10, 2])
torch.Size([10, 2])


### chunk: 갯수로 하는 방법도 있음(몇개로 만들 것인지)

In [9]:
chunks = x.chunk(2, dim=0) # 2개의 tensor로 쪼개라!
for c in chunks:
    print(c.size())

torch.Size([5, 4])
torch.Size([5, 4])


## index_select
### 원하는 index로 새로운 tensor를 만든다!

In [12]:
x = torch.FloatTensor([[[11, 12],
                       [21, 22]],
                      [[31, 32],
                       [41, 42]],
                      [[51, 52],
                       [61, 62]]])
indice = torch.LongTensor([2, 0])

x.size()

torch.Size([3, 2, 2])

In [14]:
y = x.index_select(dim=0, index=indice)
y

tensor([[[51., 52.],
         [61., 62.]],

        [[11., 12.],
         [21., 22.]]])

In [15]:
y.size()

torch.Size([2, 2, 2])

In [16]:
# 중복도 가능하다
indice = torch.LongTensor([2, 2])
y = x.index_select(dim=0, index=indice)
y

tensor([[[51., 52.],
         [61., 62.]],

        [[51., 52.],
         [61., 62.]]])

## 유용한 트릭
배치로 잘라서 나온 결과를 묶어서 하나로 만들 때 애용할 수 있다.

In [3]:
result = []
for i in range(5):
    x = torch.FloatTensor(2, 2)
    result += [x]
    print(result)

result = torch.stack(result)
result.size()

[tensor([[0., 0.],
        [0., 0.]])]
[tensor([[0., 0.],
        [0., 0.]]), tensor([[0., 0.],
        [0., 0.]])]
[tensor([[0., 0.],
        [0., 0.]]), tensor([[0., 0.],
        [0., 0.]]), tensor([[0., 0.],
        [0., 0.]])]
[tensor([[0., 0.],
        [0., 0.]]), tensor([[0., 0.],
        [0., 0.]]), tensor([[0., 0.],
        [0., 0.]]), tensor([[ 3.5873e-43,         nan],
        [-3.7765e-12,  4.5915e-41]])]
[tensor([[0., 0.],
        [0., 0.]]), tensor([[0., 0.],
        [0., 0.]]), tensor([[0., 0.],
        [0., 0.]]), tensor([[ 3.5873e-43,         nan],
        [-3.7765e-12,  4.5915e-41]]), tensor([[0.0000e+00, 1.4375e+04],
        [2.0104e+24, 8.0435e-43]])]


torch.Size([5, 2, 2])