# 데이터 전처리

## 데이터 인코딩

### 레이블 인코딩

In [2]:
from sklearn.preprocessing import LabelEncoder # sklearn의 preprocessing 모듈에서 LabelEncoder 클래스를 가져옴

In [3]:
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '믹서', '믹서'] # 데이터 lable 예시

# LabelEncoder를 객체로 생성한 후, fit()과 transform()으로 레이블 인코딩 수행
encoder = LabelEncoder() # LabelEncoder를 객체로 만듬
encoder.fit(items) # label을 encoding 함
labels = encoder.transform(items) # 레이블을 encoding한 결과를 저장
print('인코딩 변환값:' , labels)

인코딩 변환값: [0 1 4 5 3 2 2]


In [4]:
encoder.classes_ # encoding 변환된 index가 어떤 클래스인지 보여줌 

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [5]:
# inverse_transform을 통해 encoding된 값을 다시 decoding 할 수 있음
print('디코딩 원본 값:', encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3]))

디코딩 원본 값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


### 원-핫 인코딩(One-Hot Encoding)

Label Encoding은 텍스트 데이터를 수치로 변환한다. 이때 주의 해야 할 점은 클래스를 구별하는 이 숫자가 학습에 영향을 받아선 안된다는 점이다.  
숫자의 크기가 계산에 적용되면 값으 차이로 인한 성능에 영향을 줄 수 있다. 따라서 회귀 분석에는 이러한 Label Encoding을 사용하지 않는다. 

이런 문제를 보완한 Encoding 방법이 바로 One-Hot Encoding이다.

In [6]:
# 원-핫 엔코딩을 하기 전에 주의해야 할 것
# 1. 모든 값이 숫자형으로 변환돼 있어야 함.
# 2. 입력값은 2차원 데이터여야 함.

from sklearn.preprocessing import OneHotEncoder # preprosessing 모듈에서 OneHotEncoder 클래스를 가져옴
import numpy as np

In [7]:
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서'] # 데이터 셈플

In [13]:
# 먼저 숫자 값으로 변환을 위해 LabelEncoder로 변환함
encoder = LabelEncoder() # LabelEncoder 객체를 선언
encoder.fit(items) # items에 LabelEncoder를 적용함
labels = encoder.transform(items) # items를 LabelEncoder 결과로 변환함

In [14]:
labels, labels.shape

(array([0, 1, 4, 5, 3, 3, 2, 2]), (8,))

In [15]:
# 2차원 데이터로 만듬
labels = labels.reshape(-1, 1)
labels, labels.shape

(array([[0],
        [1],
        [4],
        [5],
        [3],
        [3],
        [2],
        [2]]),
 (8, 1))

In [16]:
# 원-핫 인코딩을 적용
oh_encoder = OneHotEncoder() # OneHotEncoder 객체를 선언
oh_encoder.fit(labels) # labels를 OneHotEncoder로 encoding함

oh_labels = oh_encoder.transform(labels) # labels를 oh_encoder로 변환함


In [17]:
print('원핫 인코딩 데이터')
print(oh_labels.toarray())
print('원핫 인코딩 데이터 차원')
print(oh_labels.shape)

원핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원핫 인코딩 데이터 차원
(8, 6)


In [18]:
# 그런데 위의 번거로운 작업을 할 필요가 없음. pandas에 매우 편한 get_dummies()가 있기 때문
import pandas as pd

df = pd.DataFrame({'item' : ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']}) # 1차원 데이터 생성
pd.get_dummies(df) # df에 One-Hot Encoding을 수행

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

In [19]:
df

item
0     TV
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5    선풍기
6     믹서
7     믹서