# PyTorch AutoGrad

In [1]:
import torch

In [2]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]]).requires_grad_(True) # 예로도 미분해서 파라미터 업데이트를 할거니? Yes
x

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [3]:
x1 = x + 2
x2 = x - 2
x3 = x1 * x2
y = x3.sum()

In [18]:
x3

tensor([[-3.,  0.],
        [ 5., 12.]])

In [4]:
x1.backward() # backward는 scalar여아만 한다. 

RuntimeError: grad can be implicitly created only for scalar outputs

In [5]:
y.backward()

In [14]:
x.grad

tensor([[2., 4.],
        [6., 8.]])

In [12]:
z = torch.FloatTensor([[3,5],
                   [6,1]]).requires_grad_(True)

In [16]:
x3.retain_grad()

In [17]:
x3.detach_().numpy()

array([[-3.,  0.],
       [ 5., 12.]], dtype=float32)