In [3]:
# Repeat 노드 예제
import numpy as np
D, N = 8, 7

x = np.random.randn(1, D)
# np.repeat()이 복제 노드 역할을 한다.

y = np.repeat(x, N, axis=0) # axis 방향으로 값을 복제함

print(x.shape, y.shape)

(1, 8) (7, 8)


In [4]:
x

array([[-0.36744383, -0.88539369,  0.99626451,  0.06435673, -0.83946504,
        -1.10089157,  1.00551784,  0.49460005]])

In [5]:
y

array([[-0.36744383, -0.88539369,  0.99626451,  0.06435673, -0.83946504,
        -1.10089157,  1.00551784,  0.49460005],
       [-0.36744383, -0.88539369,  0.99626451,  0.06435673, -0.83946504,
        -1.10089157,  1.00551784,  0.49460005],
       [-0.36744383, -0.88539369,  0.99626451,  0.06435673, -0.83946504,
        -1.10089157,  1.00551784,  0.49460005],
       [-0.36744383, -0.88539369,  0.99626451,  0.06435673, -0.83946504,
        -1.10089157,  1.00551784,  0.49460005],
       [-0.36744383, -0.88539369,  0.99626451,  0.06435673, -0.83946504,
        -1.10089157,  1.00551784,  0.49460005],
       [-0.36744383, -0.88539369,  0.99626451,  0.06435673, -0.83946504,
        -1.10089157,  1.00551784,  0.49460005],
       [-0.36744383, -0.88539369,  0.99626451,  0.06435673, -0.83946504,
        -1.10089157,  1.00551784,  0.49460005]])

In [8]:
dy = np.random.randn(N, D) # 랜덤한 기울기

dx = np.sum(dy, axis=0, keepdims=True) # 역전파 # keepdims=True -> 차원수 유지함
dx_1 = np.sum(dy, axis=0)

In [9]:
print(dx.shape, dx_1.shape)

(1, 8) (8,)


In [10]:
dx

array([[ 0.59961556, -2.37712304, -0.52296305, -1.54473511, -1.24151466,
         0.59268309,  0.47692568, -3.30542937]])

In [11]:
dx_1

array([ 0.59961556, -2.37712304, -0.52296305, -1.54473511, -1.24151466,
        0.59268309,  0.47692568, -3.30542937])

### sum 노드
아래의 그림에서 확인할 수 있듯이, Sum 노드와 Repeat 노드는 서로 __'반대 관계'__ 이다.
+ Sum 노드의 순전파가 Repeat 노드의 역전파이며,
+ Sum 노드의 역전파가 Repeat 노드의 순전파가 된다.

![](https://github.com/ExcelsiorCJH/DLFromScratch2/raw/b2a7b6a8e6344830314da3ab7038b1382358d348/Chap01-Neural_Networks_Review/images/sum.png)

In [12]:
# Sum 노드 역전파 예제

import numpy as np

D, N = 8, 7
x = np.random.randn(N, D)
y = np.sum(x, axis=0, keepdims = True) # 순전파

print(x.shape, y.shape)

(7, 8) (1, 8)


In [13]:
x

array([[ 0.14047721,  1.11048588, -0.77012518, -0.78093914,  0.31036797,
         1.42033576,  2.61517144,  0.06811956],
       [-1.61745132, -0.02985062, -0.40482667, -0.12034905,  1.32736947,
        -0.07462502, -2.9418487 ,  0.35482078],
       [ 0.27939737,  1.3319824 , -2.02815951, -0.47863674,  0.15705698,
         0.18862469, -0.94997938,  0.91650379],
       [ 1.61136095, -0.21310396,  0.74585266,  1.47101364, -0.31174697,
         0.42078659,  0.74697366,  0.16811081],
       [-0.07122013, -0.09906628,  0.28722235, -0.09460307,  0.26141202,
         1.27963204, -0.77915039,  0.99456108],
       [-2.44186812, -2.63918355, -0.47693138,  1.07808563, -0.31532632,
         1.41564746,  0.69725953,  0.7369968 ],
       [ 0.16434391, -0.13934735, -0.45962269, -0.75242173, -0.04020714,
         0.13601322, -0.86919539, -1.27942486]])

In [14]:
y

array([[-1.93496014, -0.67808348, -3.10659043,  0.32214956,  1.38892602,
         4.78641473, -1.48076923,  1.95968795]])

### MatMul 노드
행렬의 곱셈 Matrix Multiply의 약자로 MatMul을 사용한다. 배치사이즈가 N이라고 할 때 MatMul 노드의 역전파는 다음과 같다.

![](https://github.com/ExcelsiorCJH/DLFromScratch2/raw/b2a7b6a8e6344830314da3ab7038b1382358d348/Chap01-Neural_Networks_Review/images/matmul.png)

In [15]:
# MatMul 클래스 구현
# common / layers.py

class MatMul:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.x = None
        
    def forward(self, x):
        W, = self.parmas
        out = np.matmul(x, W)
        self.x = x
        return out
    
    def backward(self, dout):
        W, = self.params
        dx = np.matmul(dout, W.T)
        dw = np.matmul(self.x.T, dout)
        self.grads[0][...] = dw
        return dx