# How to use GPU

In [1]:
import torch
import torch.nn as nn

## Convert to CUDA tensor:cuda()

In [4]:
x = torch.cuda.FloatTensor(2, 2) # 애초에 gpu에서 Tensor 선언하기
x

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [5]:
# 일반적으로 Tensor를 선언하고 GPU로 보내기
x.cuda()

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [6]:
# 특정 gpu 번호를 지정해서 넘겨주기
d = torch.device('cuda:0')
x.cuda(device=d)
x

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [12]:
# cpu로 복사해볼까?
x=x.cpu()
x

tensor([[0., 0.],
        [0., 0.]])

In [16]:
d = torch.device('cpu')
x=x.to(d)
x

tensor([[0., 0.],
        [0., 0.]])

In [17]:
x = x.cuda()
x

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')