# Tensor 실습

In [1]:
import torch

In [3]:
# 32bit의 float 텐서
ft = torch.FloatTensor([[1, 2],
                        [3, 4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [5]:
# 정수형 텐
lt = torch.LongTensor([[1, 2],
                      [3, 4]])
lt

tensor([[1, 2],
        [3, 4]])

In [8]:
# Boolean  텐서
bt = torch.BoolTensor([[True, False],
                        [0, 1]])
bt

tensor([[ True, False],
        [ True, False]])

In [9]:
# 값은 랜덤하게 만들고, size만 지정해서 만든 텐서
x = torch.FloatTensor(3, 2)
x

tensor([[0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.0194e-38]])

## 파이토치의 장점은 Numpy와 호환성이 좋다

In [11]:
import numpy as np

# numpy array 하나 만들자
np_arr = np.array([[1, 2],
                  [3, 4]])
print(np_arr, type(np_arr))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [12]:
# torch의 텐서로 변환
torch_arr = torch.from_numpy(np_arr)
print(torch_arr, type(torch_arr))

tensor([[1, 2],
        [3, 4]], dtype=torch.int32) <class 'torch.Tensor'>


In [13]:
np_arr_from_torch = torch_arr.numpy()
print(np_arr_from_torch, type(np_arr_from_torch))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


## 텐서의 타입 변환

In [16]:
# float tensor -> long tensor
ft.long()

tensor([[1, 2],
        [3, 4]])

In [18]:
lt.float()

tensor([[1., 2.],
        [3., 4.]])

In [19]:
torch.FloatTensor([1, 0]).byte()

tensor([1, 0], dtype=torch.uint8)

# 텐서의 shape 살펴보기

In [23]:
x.size()

torch.Size([3, 2])

In [24]:
x.shape

torch.Size([3, 2])

In [25]:
x.dim()

2

In [26]:
len(x.size())

2