# GD

In [1]:
import torch
import torch.nn.functional as F

In [8]:
target = torch.FloatTensor([[0.1, 0.2, 0.3],
                            [0.4, 0.5, 0.6],
                            [0.7, 0.8, 0.9]])
target

tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000],
        [0.7000, 0.8000, 0.9000]])

In [9]:
x = torch.rand_like(target)

# 아래 코드는 최종 스칼라 값이 x로 미분된다는 것을 뜻함
x.requires_grad = True
x

tensor([[0.5354, 0.7055, 0.9260],
        [0.9693, 0.3723, 0.5890],
        [0.3125, 0.3422, 0.2985]], requires_grad=True)

In [10]:
loss = F.mse_loss(x, target)
loss

tensor(0.2110, grad_fn=<MseLossBackward0>)

In [6]:
# GD를 바닥부터 구현해보자.

threshold = 1e-5 # 이것보다 작으면 학습 완료
lr = 0.5
iter_cnt = 0

while loss > threshold:
    iter_cnt += 1
    loss.backward() # loss에 대해서 x로 미분!
    
    x = x - lr * x.grad # 파라미터 업데이트 수식 그 자체
    
    x.detach_()
    x.requires_grad_(True)
    
    loss = F.mse_loss(x, target) # loss update
    
    print('{}-th Loss: {}'.format(iter_cnt, loss))
    print(x)
    

1-th Loss: 0.09444469958543777
tensor([[0.6541, 0.5584, 0.0372],
        [0.7159, 0.3582, 0.5254],
        [0.7731, 0.3368, 0.9120]], requires_grad=True)
2-th Loss: 0.0746229737997055
tensor([[0.5925, 0.5186, 0.0664],
        [0.6808, 0.3740, 0.5337],
        [0.7650, 0.3883, 0.9107]], requires_grad=True)
3-th Loss: 0.05896135792136192
tensor([[0.5378, 0.4832, 0.0923],
        [0.6496, 0.3880, 0.5411],
        [0.7578, 0.4340, 0.9095]], requires_grad=True)
4-th Loss: 0.04658675566315651
tensor([[0.4891, 0.4517, 0.1154],
        [0.6219, 0.4004, 0.5476],
        [0.7514, 0.4747, 0.9084]], requires_grad=True)
5-th Loss: 0.0368092842400074
tensor([[0.4459, 0.4238, 0.1359],
        [0.5972, 0.4115, 0.5534],
        [0.7456, 0.5108, 0.9075]], requires_grad=True)
6-th Loss: 0.02908387780189514
tensor([[0.4075, 0.3989, 0.1541],
        [0.5753, 0.4213, 0.5586],
        [0.7406, 0.5430, 0.9067]], requires_grad=True)
7-th Loss: 0.0229798574000597
tensor([[0.3733, 0.3768, 0.1703],
        [0.555

오우 개쩐다! ㅋㅋ

In [11]:
# lr을 바꿔보자. 어떤 변화가 있을까.

threshold = 1e-5 # 이것보다 작으면 학습 완료
lr = 1.
iter_cnt = 0

while loss > threshold:
    iter_cnt += 1
    loss.backward() # loss에 대해서 x로 미분!
    
    x = x - lr * x.grad # 파라미터 업데이트 수식 그 자체
    
    x.detach_()
    x.requires_grad_(True)
    
    loss = F.mse_loss(x, target) # loss update
    
    print('{}-th Loss: {}'.format(iter_cnt, loss))
    print(x)
    

1-th Loss: 0.12764540314674377
tensor([[0.4387, 0.5932, 0.7869],
        [0.8428, 0.4007, 0.5914],
        [0.3986, 0.4440, 0.4322]], requires_grad=True)
2-th Loss: 0.07721758633852005
tensor([[0.3634, 0.5058, 0.6787],
        [0.7444, 0.4228, 0.5933],
        [0.4656, 0.5231, 0.5361]], requires_grad=True)
3-th Loss: 0.04671187326312065
tensor([[0.3049, 0.4378, 0.5945],
        [0.6679, 0.4399, 0.5948],
        [0.5177, 0.5846, 0.6170]], requires_grad=True)
4-th Loss: 0.02825779654085636
tensor([[0.2593, 0.3850, 0.5291],
        [0.6083, 0.4533, 0.5960],
        [0.5582, 0.6325, 0.6799]], requires_grad=True)
5-th Loss: 0.017094220966100693
tensor([[0.2239, 0.3439, 0.4782],
        [0.5620, 0.4637, 0.5969],
        [0.5897, 0.6697, 0.7288]], requires_grad=True)
6-th Loss: 0.010340948589146137
tensor([[0.1964, 0.3119, 0.4386],
        [0.5260, 0.4717, 0.5976],
        [0.6142, 0.6987, 0.7668]], requires_grad=True)
7-th Loss: 0.006255635991692543
tensor([[0.1750, 0.2870, 0.4078],
        

오차는 좀 크지만 훨씬 빨리 수렴했네.