# 텐서 사이즈 이모저모

In [2]:
import torch

In [6]:
a = torch.FloatTensor(1, 2, 3, 1)
a, a.size()

(tensor([[[[0.0000e+00],
           [9.9184e-39],
           [1.8754e+28]],
 
          [[3.2175e+21],
           [4.1727e-08],
           [1.2802e-11]]]]),
 torch.Size([1, 2, 3, 1]))

## reshape

## squeeze
1. 텐서에서 크기가 1인 차원을 제거한다!
2. 특정 차원에 대해서만 제거할 수도 있다. 

In [7]:
a.squeeze().size()

torch.Size([2, 3])

In [8]:
a.squeeze(0).size()

torch.Size([2, 3, 1])

## unsqueeze
특정 차원을 늘려준다.

In [9]:
b = torch.FloatTensor(2, 3)
b, b.shape

(tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 8.9082e-39]]),
 torch.Size([2, 3]))

In [10]:
b.unsqueeze(-1).size()

torch.Size([2, 3, 1])

In [12]:
b.unsqueeze(1)

tensor([[[0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 8.9082e-39]]])