In [1]:
import torch

In [4]:
a = torch.FloatTensor([[3, 5],
                       [1, 10]])
b = torch.FloatTensor([[13, 0],
                        [-4, 2]])
a, b

(tensor([[ 3.,  5.],
         [ 1., 10.]]),
 tensor([[13.,  0.],
         [-4.,  2.]]))

## Inplace 연산

In [5]:
a.mul(b)

tensor([[39.,  0.],
        [-4., 20.]])

In [6]:
a

tensor([[ 3.,  5.],
        [ 1., 10.]])

In [7]:
a.mul_(b)

tensor([[39.,  0.],
        [-4., 20.]])

In [8]:
a

tensor([[39.,  0.],
        [-4., 20.]])

# 주의!

### 브로드캐스트 때문에 죽어야 할 코드가 죽지 않고 예기치 않은 연산이 나올 수 있다.