In [5]:
import torch

In [23]:
x = torch.randperm(3*2*3).reshape(3, 2, 3) # 중복되지 않는 배열
print(x)
print(x.size())

tensor([[[15,  8, 12],
         [17, 16, 11]],

        [[ 7,  1,  2],
         [ 9, 13, 10]],

        [[ 5, 14,  4],
         [ 6,  0,  3]]])
torch.Size([3, 2, 3])


## argmax : 가장 큰 값을 가진 index를 알 수 있다.

In [24]:
y = x.argmax(dim=1)
print(y)
y.size()

tensor([[1, 1, 0],
        [1, 1, 1],
        [1, 0, 0]])


torch.Size([3, 3])

## topk: tok-k인 index와 값을 알 수 있다.

In [25]:
values, indice = torch.topk(x, k=1, dim=1)
print(values)
print(indice)
print(values.size())

tensor([[[17, 16, 12]],

        [[ 9, 13, 10]],

        [[ 6, 14,  4]]])
tensor([[[1, 1, 0]],

        [[1, 1, 1]],

        [[1, 0, 0]]])
torch.Size([3, 1, 3])
