# Singular Value Decomposition, SVD

특이값 분해는 행렬을 3개의 행렬의 곱의 형태로 분해하는 것이다.  
$ A = U\Sigma V^T$  (직교, 대각, 직교)  
직교행렬: n x n 행렬 A에 대하여 $ A \times A^T = I$이면서 $A^T\times A = I$인 행렬이다. 즉, $A^{-1} = A^T$를 만족한다



In [1]:
import numpy as np

In [2]:
A = np.array(
    [
        [0,0,0,1,0,1,1,0,0],
        [0,0,0,1,1,0,1,0,0],
        [0,1,1,0,2,0,0,0,0],
        [1,0,0,0,0,0,0,1,1]
    ]
)
print('DTM의 크기(shape) :', np.shape(A))

DTM의 크기(shape) : (4, 9)


Full SVD

In [3]:
# 특이값 분해
U, s, VT = np.linalg.svd(A, full_matrices=True)
print('행렬 U :')
print(U.round(2))
print('행렬 U의 크기(shape) :',np.shape(U))

행렬 U :
[[-0.24  0.75  0.   -0.62]
 [-0.51  0.44 -0.    0.74]
 [-0.83 -0.49 -0.   -0.27]
 [-0.   -0.    1.    0.  ]]
행렬 U의 크기(shape) : (4, 4)


In [5]:
print('특이값 벡터 :')
print(s.round(2))
print('특이값 벡터의 크기(shape) :',np.shape(s))

특이값 벡터 :
[2.69 2.05 1.73 0.77]
특이값 벡터의 크기(shape) : (4,)


Numpy의 linalg.svd()는 특이값 분해의 결과로 대각 행렬이 아니라 특이값의 리스트를 반환합니다.  
그러므로 앞서 본 수식의 형식으로 보려면 이를 다시 대각 행렬로 바꾸어 주어야 합니다.  
우선 특이값을 s에 저장하고 대각 행렬 크기의 행렬을 생성한 후에 그 행렬에 특이값을 삽입해도록 하겠습니다.

In [6]:
# 대각 행렬의 크기인 4 x 9의 임의의 행렬 생성
S = np.zeros((4, 9))

# 특이값을 대각행렬에 삽입
S[:4, :4] = np.diag(s) # diagonal 대각행렬을 만드는 함수

print('대각 행렬 S :')
print(S.round(2))

print('대각 행렬의 크기(shape) :')
print(np.shape(S))

대각 행렬 S :
[[2.69 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   2.05 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   1.73 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.77 0.   0.   0.   0.   0.  ]]
대각 행렬의 크기(shape) :
(4, 9)


In [7]:
np.diag(s) # 대각행렬의 값은 내림차순되어있

array([[2.68731789, 0.        , 0.        , 0.        ],
       [0.        , 2.04508425, 0.        , 0.        ],
       [0.        , 0.        , 1.73205081, 0.        ],
       [0.        , 0.        , 0.        , 0.77197992]])

In [8]:
print('직교행렬 VT :')
print(VT.round(2))

print('직교 행렬 VT의 크기(shape) :')
print(np.shape(VT))

직교행렬 VT :
[[-0.   -0.31 -0.31 -0.28 -0.8  -0.09 -0.28 -0.   -0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58 -0.   -0.  ]
 [ 0.58 -0.    0.    0.   -0.    0.   -0.    0.58  0.58]
 [ 0.   -0.35 -0.35  0.16  0.25 -0.8   0.16 -0.   -0.  ]
 [-0.   -0.78 -0.01 -0.2   0.4   0.4  -0.2   0.    0.  ]
 [-0.29  0.31 -0.78 -0.24  0.23  0.23  0.01  0.14  0.14]
 [-0.29 -0.1   0.26 -0.59 -0.08 -0.08  0.66  0.14  0.14]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19  0.75 -0.25]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19 -0.25  0.75]]
직교 행렬 VT의 크기(shape) :
(9, 9)


분해된 행렬을 곱하면 원래 행렬이 나와야한다.  
이 확인은 numpy의 allclose() 함수를 사용해서 알아보자. 두 행렬이 같으면 True를 리턴한다

In [9]:
np.allclose(A, np.dot(np.dot(U,S), VT).round(2))

True

# 절단된 SVD
절단된 SVD는 분해된 행렬의 t 크기만큼만 사용하게 되는데, 이 t값이 남길 정보량을 결정하는 하이퍼파라미터다.  
t에는 중요한 정보가 남고 나머지는 상대적으로 의미가 없는 정보가 버려지게된다. 

In [11]:
S = S[:2, :2]

print("절단된 대각 행렬 S: ")
print(S.round(2))

대각 행렬 S: 
[[2.69 0.  ]
 [0.   2.05]]


In [12]:
U = U[:, :2]
print("절단된 행렬 U :")
print(U.round(2))

절단된 행렬 U :
[[-0.24  0.75]
 [-0.51  0.44]
 [-0.83 -0.49]
 [-0.   -0.  ]]


In [13]:
VT = VT[:2, :]
print("절단된 직교행렬 VT:")
print(VT.round(2))

절단된 직교행렬 VT:
[[-0.   -0.31 -0.31 -0.28 -0.8  -0.09 -0.28 -0.   -0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58 -0.   -0.  ]]


In [14]:
A_prime = np.dot(np.dot(U, S), VT)
print(A)
print(A_prime.round(2))

[[0 0 0 1 0 1 1 0 0]
 [0 0 0 1 1 0 1 0 0]
 [0 1 1 0 2 0 0 0 0]
 [1 0 0 0 0 0 0 1 1]]
[[ 0.   -0.17 -0.17  1.08  0.12  0.62  1.08 -0.   -0.  ]
 [ 0.    0.2   0.2   0.91  0.86  0.45  0.91  0.    0.  ]
 [ 0.    0.93  0.93  0.03  2.05 -0.17  0.03  0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.  ]]


# 실습!
